# Generated by Django 5.2.10 on 2026-02-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_num', models.IntegerField(unique=True)),
                ('ins_types', models.CharField(choices=[('GO', 'GO'), ('KASKO', 'KASKO'), ('ROBBERY', 'ROBBERY'), ('OTHER', 'OTHER')], default='OTHER', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rescheduled', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('rescheduled_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='vehicles.vehicle')),
            ],
        ),
    ]
