# Generated by Django 5.2.10 on 2026-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='ins_types',
            field=models.CharField(choices=[('GO', 'Гражданска отговорност'), ('KASKO', 'Пълно каско'), ('ROBBERY', 'Кражба'), ('OTHER', 'Друго')], default='OTHER', max_length=10),
        ),
    ]
