# Generated by Django 5.2.10 on 2026-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurance_ins_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='policy_num',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
