# Generated by Django 5.2.10 on 2026-02-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_insurance_policy_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='ins_types',
            field=models.CharField(choices=[('GO', 'ГО'), ('KASKO', 'Каско'), ('ROBBERY', 'Кражба'), ('OTHER', 'Друго')], default='OTHER', max_length=10),
        ),
    ]
