# Generated by Django 5.2.10 on 2026-02-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intermediaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('owner_ucn', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('city', models.CharField(default='Sofia', max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('tel_num', models.CharField(max_length=10, unique=True)),
                ('intermediaries', models.ManyToManyField(blank=True, related_name='customers', to='intermediaries.intermediary')),
            ],
        ),
    ]
