# Generated by Django 5.2.10 on 2026-02-09 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10, unique=True)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('vin_num', models.CharField(max_length=17, unique=True)),
                ('date_of_first_registration', models.DateField()),
                ('engine_capacity', models.IntegerField()),
                ('type_of_fuel', models.CharField(choices=[('Petrol', 'Бензин'), ('Diesel', 'Дизел'), ('Hybrid', 'Хибрид'), ('Electric', 'Електрическа')], max_length=15)),
                ('color', models.CharField(default='without', max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
